# Generated by Django 4.2.29 on 2026-03-16 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='usuarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', through='projects.Assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
