# Generated by Django 4.2.30 on 2026-10-05 20:57

import campo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_usuarios_asignados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(help_text='Qué se necesita y en qué cantidad (texto libre).')),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENTREGADA', 'Entregada')], default='PENDIENTE', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('gestionada_en', models.DateTimeField(blank=True, null=True)),
                ('entregada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_insumo', to=settings.AUTH_USER_MODEL)),
                ('gestionada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_insumo', to='projects.project')),
            ],
            options={
                'verbose_name': 'Solicitud de insumos',
                'verbose_name_plural': 'Solicitudes de insumos',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('SEGURIDAD', 'Seguridad'), ('DANO_FALLA', 'Daño o falla'), ('RETRASO', 'Retraso o bloqueo'), ('PERSONAL', 'Personal'), ('OTRA', 'Otra')], default='OTRA', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hecho', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ATENDIDA', 'Atendida')], default='ABIERTA', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='projects.project')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='InformeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_servicio', models.DateField(default=django.utils.timezone.localdate)),
                ('ubicacion', models.CharField(blank=True, max_length=300)),
                ('actividades', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('firma_nombre', models.CharField(blank=True, max_length=200)),
                ('firma_cargo', models.CharField(blank=True, max_length=200)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to=campo.models.ruta_firma)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto')], default='BORRADOR', max_length=20)),
                ('comentario_revision', models.TextField(blank=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=campo.models.ruta_pdf)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='informes_participados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='projects.project')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe de servicio',
                'verbose_name_plural': 'Informes de servicio',
                'ordering': ['-fecha_servicio', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=campo.models.ruta_foto)),
                ('miniatura', models.ImageField(upload_to=campo.models.ruta_miniatura)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='campo.informeservicio')),
                ('novedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='campo.novedad')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='campo.solicitudinsumo')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOVEDAD', 'Novedad'), ('INSUMO', 'Insumos'), ('INFORME', 'Informe')], max_length=20)),
                ('texto', models.CharField(max_length=300)),
                ('enlace', models.CharField(blank=True, max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['destinatario', 'leida'], name='campo_notif_destina_59e5e2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='foto',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('informe__isnull', True), ('novedad__isnull', False), ('solicitud__isnull', True)), models.Q(('informe__isnull', True), ('novedad__isnull', True), ('solicitud__isnull', False)), models.Q(('informe__isnull', False), ('novedad__isnull', True), ('solicitud__isnull', True)), _connector='OR'), name='foto_un_solo_padre'),
        ),
    ]
