# Generated by Django 4.2.29 on 2026-03-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0001_initial'),
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_tiempo', to='cuadrillas.cuadrilla'),
        ),
    ]
